// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService is bound to the frontend: the GUI's own version and relaunching itself.
 * Updates are installed by the daemon; the host only quits and reopens the window.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Info returns the GUI's version and bundle path.
 */
export function Info(): $CancellablePromise<$models.AppInfo> {
    return $Call.ByID(3943185810);
}

/**
 * Relaunch quits the app and opens it again once this process has exited, so the new
 * process runs whatever bundle is on disk now (an installed update). Sessions are
 * unaffected: they live in the daemon.
 */
export function Relaunch(): $CancellablePromise<void> {
    return $Call.ByID(3512615560);
}
