// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DaemonService is bound to the frontend. It is the only thing the Wails host exposes.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetDaemonEndpoint ensures the daemon is running (starting it if needed) and returns
 * its loopback base URL and bearer token. The frontend calls it at startup and again
 * whenever a request fails, which picks up a restarted daemon's new port and token.
 */
export function GetDaemonEndpoint(): $CancellablePromise<$models.DaemonEndpoint> {
    return $Call.ByID(3057854678);
}
