// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DaemonEndpoint is how the frontend reaches the daemon's loopback listener.
 */
export interface DaemonEndpoint {
    "baseUrl": string;
    "token": string;
}
