// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppInfo is what the frontend knows about the window shell itself.
 */
export interface AppInfo {
    /**
     * Version is this GUI binary's version (same ldflag as the daemon's).
     */
    "version": string;

    /**
     * Bundle is the .app this GUI runs from, or "" for a dev binary.
     */
    "bundle": string;
}

/**
 * DaemonEndpoint is how the frontend reaches the daemon's loopback listener.
 */
export interface DaemonEndpoint {
    "baseUrl": string;
    "token": string;
}
